let data = [{
    "ConferenceID": 1,
    "Name": "American Athletic - East",
    "Teams": [{
      "TeamID": 2,
      "Key": "TEMPL",
      "Active": true,
      "School": "Temple",
      "Name": "Owls",
      "StadiumID": 21,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000002,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/2.png",
      "ConferenceID": 1,
      "Conference": "American Athletic - East"
    }, {
      "TeamID": 3,
      "Key": "UCONN",
      "Active": true,
      "School": "UConn",
      "Name": "Huskies",
      "StadiumID": 5,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000003,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/3.png",
      "ConferenceID": 1,
      "Conference": "American Athletic - East"
    }, {
      "TeamID": 4,
      "Key": "CIN",
      "Active": true,
      "School": "Cincinnati",
      "Name": "Bearcats",
      "StadiumID": 4,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000004,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/4.png",
      "ConferenceID": 1,
      "Conference": "American Athletic - East"
    }, {
      "TeamID": 8,
      "Key": "UCF",
      "Active": true,
      "School": "UCF",
      "Name": "Knights",
      "StadiumID": 63,
      "ApRank": 6,
      "Wins": 13,
      "Losses": 0,
      "ConferenceWins": 8,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000008,
      "CoachesRank": 7,
      "PlayoffRank": 12,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/8.png",
      "ConferenceID": 1,
      "Conference": "American Athletic - East"
    }, {
      "TeamID": 9,
      "Key": "ECAR",
      "Active": true,
      "School": "East Carolina",
      "Name": "Pirates",
      "StadiumID": 54,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000009,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/9.png",
      "ConferenceID": 1,
      "Conference": "American Athletic - East"
    }, {
      "TeamID": 11,
      "Key": "SFL",
      "Active": true,
      "School": "South Florida",
      "Name": "Bulls",
      "StadiumID": 62,
      "ApRank": 21,
      "Wins": 10,
      "Losses": 2,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000011,
      "CoachesRank": 21,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/11.png",
      "ConferenceID": 1,
      "Conference": "American Athletic - East"
    }]
  }, {
    "ConferenceID": 2,
    "Name": "American Athletic - West",
    "Teams": [{
      "TeamID": 1,
      "Key": "SMU",
      "Active": true,
      "School": "SMU",
      "Name": "Mustangs",
      "StadiumID": 130,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000001,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/1.png",
      "ConferenceID": 2,
      "Conference": "American Athletic - West"
    }, {
      "TeamID": 10,
      "Key": "TULANE",
      "Active": true,
      "School": "Tulane",
      "Name": "Green Wave",
      "StadiumID": 112,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000010,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/10.png",
      "ConferenceID": 2,
      "Conference": "American Athletic - West"
    }, {
      "TeamID": 5,
      "Key": "TULSA",
      "Active": true,
      "School": "Tulsa",
      "Name": "Golden Hurricane",
      "StadiumID": 61,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000005,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/5.png",
      "ConferenceID": 2,
      "Conference": "American Athletic - West"
    }, {
      "TeamID": 6,
      "Key": "HOU",
      "Active": true,
      "School": "Houston",
      "Name": "Cougars",
      "StadiumID": 84,
      "ApRank": null,
      "Wins": 7,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000006,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/6.png",
      "ConferenceID": 2,
      "Conference": "American Athletic - West"
    }, {
      "TeamID": 7,
      "Key": "MPHS",
      "Active": true,
      "School": "Memphis",
      "Name": "Tigers",
      "StadiumID": 65,
      "ApRank": 25,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000007,
      "CoachesRank": 24,
      "PlayoffRank": 20,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/7.png",
      "ConferenceID": 2,
      "Conference": "American Athletic - West"
    }, {
      "TeamID": 258,
      "Key": "NAVY",
      "Active": true,
      "School": "Navy",
      "Name": "Midshipmen",
      "StadiumID": 29,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000258,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/258.png",
      "ConferenceID": 2,
      "Conference": "American Athletic - West"
    }]
  }, {
    "ConferenceID": 3,
    "Name": "Atlantic",
    "Teams": [{
      "TeamID": 24,
      "Key": "LOU",
      "Active": true,
      "School": "Louisville",
      "Name": "Cardinals",
      "StadiumID": 121,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000024,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/24.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }, {
      "TeamID": 27,
      "Key": "CLMSN",
      "Active": true,
      "School": "Clemson",
      "Name": "Tigers",
      "StadiumID": 90,
      "ApRank": 4,
      "Wins": 12,
      "Losses": 2,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000027,
      "CoachesRank": 4,
      "PlayoffRank": 1,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/27.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }, {
      "TeamID": 29,
      "Key": "FLST",
      "Active": true,
      "School": "Florida State",
      "Name": "Seminoles",
      "StadiumID": 89,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000029,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/29.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }, {
      "TeamID": 30,
      "Key": "SYRA",
      "Active": true,
      "School": "Syracuse",
      "Name": "Orange",
      "StadiumID": 20,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000030,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/30.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }, {
      "TeamID": 33,
      "Key": "NCST",
      "Active": true,
      "School": "NC State",
      "Name": "Wolfpack",
      "StadiumID": 6,
      "ApRank": 23,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000033,
      "CoachesRank": 23,
      "PlayoffRank": 24,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/33.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }, {
      "TeamID": 34,
      "Key": "WAKE",
      "Active": true,
      "School": "Wake Forest",
      "Name": "Demon Deacons",
      "StadiumID": 3,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000034,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/34.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }, {
      "TeamID": 35,
      "Key": "BOSCOL",
      "Active": true,
      "School": "Boston College",
      "Name": "Eagles",
      "StadiumID": 134,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000035,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/35.png",
      "ConferenceID": 3,
      "Conference": "Atlantic"
    }]
  }, {
    "ConferenceID": 4,
    "Name": "Coastal",
    "Teams": [{
      "TeamID": 31,
      "Key": "VTECH",
      "Active": true,
      "School": "Virginia Tech",
      "Name": "Hokies",
      "StadiumID": 38,
      "ApRank": 24,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000031,
      "CoachesRank": 25,
      "PlayoffRank": 22,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/31.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }, {
      "TeamID": 32,
      "Key": "GTECH",
      "Active": true,
      "School": "Georgia Tech",
      "Name": "Yellow Jackets",
      "StadiumID": 92,
      "ApRank": null,
      "Wins": 5,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000032,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/32.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }, {
      "TeamID": 28,
      "Key": "PITT",
      "Active": true,
      "School": "Pittsburgh",
      "Name": "Panthers",
      "StadiumID": 39,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000028,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/28.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }, {
      "TeamID": 21,
      "Key": "NCAR",
      "Active": true,
      "School": "North Carolina",
      "Name": "Tar Heels",
      "StadiumID": 127,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000021,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/21.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }, {
      "TeamID": 22,
      "Key": "VIR",
      "Active": true,
      "School": "Virginia",
      "Name": "Cavaliers",
      "StadiumID": 44,
      "ApRank": null,
      "Wins": 6,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000022,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/22.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }, {
      "TeamID": 23,
      "Key": "MIA",
      "Active": true,
      "School": "Miami",
      "Name": "Hurricanes",
      "StadiumID": 55,
      "ApRank": 13,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000023,
      "CoachesRank": 13,
      "PlayoffRank": 10,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/23.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }, {
      "TeamID": 26,
      "Key": "DUKE",
      "Active": true,
      "School": "Duke",
      "Name": "Blue Devils",
      "StadiumID": 53,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000026,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/26.png",
      "ConferenceID": 4,
      "Conference": "Coastal"
    }]
  }, {
    "ConferenceID": 5,
    "Name": "Big 12 Conference",
    "Teams": [{
      "TeamID": 105,
      "Key": "OKL",
      "Active": true,
      "School": "Oklahoma",
      "Name": "Sooners",
      "StadiumID": 105,
      "ApRank": 3,
      "Wins": 12,
      "Losses": 2,
      "ConferenceWins": 8,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000105,
      "CoachesRank": 3,
      "PlayoffRank": 2,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/105.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 106,
      "Key": "KAN",
      "Active": true,
      "School": "Kansas",
      "Name": "Jayhawks",
      "StadiumID": 64,
      "ApRank": null,
      "Wins": 1,
      "Losses": 11,
      "ConferenceWins": 0,
      "ConferenceLosses": 9,
      "GlobalTeamID": 50000106,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/106.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 107,
      "Key": "WVIR",
      "Active": true,
      "School": "West Virginia",
      "Name": "Mountaineers",
      "StadiumID": 36,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 5,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000107,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/107.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 108,
      "Key": "BAYL",
      "Active": true,
      "School": "Baylor",
      "Name": "Bears",
      "StadiumID": 23,
      "ApRank": null,
      "Wins": 1,
      "Losses": 11,
      "ConferenceWins": 1,
      "ConferenceLosses": 8,
      "GlobalTeamID": 50000108,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/108.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 109,
      "Key": "TX",
      "Active": true,
      "School": "Texas",
      "Name": "Longhorns",
      "StadiumID": 82,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 5,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000109,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/109.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 110,
      "Key": "IOWAST",
      "Active": true,
      "School": "Iowa State",
      "Name": "Cyclones",
      "StadiumID": 71,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000110,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/110.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 111,
      "Key": "TXTECH",
      "Active": true,
      "School": "Texas Tech",
      "Name": "Red Raiders",
      "StadiumID": 76,
      "ApRank": null,
      "Wins": 6,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000111,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/111.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 112,
      "Key": "KANST",
      "Active": true,
      "School": "Kansas State",
      "Name": "Wildcats",
      "StadiumID": 123,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000112,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/112.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 113,
      "Key": "OKST",
      "Active": true,
      "School": "Oklahoma State",
      "Name": "Cowboys",
      "StadiumID": 48,
      "ApRank": 14,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 6,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000113,
      "CoachesRank": 14,
      "PlayoffRank": 19,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/113.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }, {
      "TeamID": 114,
      "Key": "TCU",
      "Active": true,
      "School": "TCU",
      "Name": "Horned Frogs",
      "StadiumID": 75,
      "ApRank": 9,
      "Wins": 11,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000114,
      "CoachesRank": 9,
      "PlayoffRank": 15,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/114.png",
      "ConferenceID": 5,
      "Conference": "Big 12 Conference"
    }]
  }, {
    "ConferenceID": 6,
    "Name": "Big Ten - East",
    "Teams": [{
      "TeamID": 92,
      "Key": "MARY",
      "Active": true,
      "School": "Maryland",
      "Name": "Terrapins",
      "StadiumID": 37,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 2,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000092,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/92.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }, {
      "TeamID": 93,
      "Key": "IND",
      "Active": true,
      "School": "Indiana",
      "Name": "Hoosiers",
      "StadiumID": 100,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 2,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000093,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/93.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }, {
      "TeamID": 97,
      "Key": "MST",
      "Active": true,
      "School": "Michigan State",
      "Name": "Spartans",
      "StadiumID": 22,
      "ApRank": 15,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000097,
      "CoachesRank": 16,
      "PlayoffRank": 16,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/97.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }, {
      "TeamID": 98,
      "Key": "OHIOST",
      "Active": true,
      "School": "Ohio State",
      "Name": "Buckeyes",
      "StadiumID": 31,
      "ApRank": 5,
      "Wins": 12,
      "Losses": 2,
      "ConferenceWins": 8,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000098,
      "CoachesRank": 5,
      "PlayoffRank": 5,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/98.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }, {
      "TeamID": 95,
      "Key": "MICH",
      "Active": true,
      "School": "Michigan",
      "Name": "Wolverines",
      "StadiumID": 33,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000095,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/95.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }, {
      "TeamID": 101,
      "Key": "PENNST",
      "Active": true,
      "School": "Penn State",
      "Name": "Nittany Lions",
      "StadiumID": 122,
      "ApRank": 8,
      "Wins": 11,
      "Losses": 2,
      "ConferenceWins": 7,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000101,
      "CoachesRank": 8,
      "PlayoffRank": 9,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/101.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }, {
      "TeamID": 103,
      "Key": "RUTGER",
      "Active": true,
      "School": "Rutgers",
      "Name": "Scarlet Knights",
      "StadiumID": 85,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 3,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000103,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/103.png",
      "ConferenceID": 6,
      "Conference": "Big Ten - East"
    }]
  }, {
    "ConferenceID": 7,
    "Name": "Big Ten - West",
    "Teams": [{
      "TeamID": 104,
      "Key": "MINNST",
      "Active": true,
      "School": "Minnesota",
      "Name": "Golden Gophers",
      "StadiumID": 13,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 2,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000104,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/104.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }, {
      "TeamID": 102,
      "Key": "ILL",
      "Active": true,
      "School": "Illinois",
      "Name": "Fighting Illini",
      "StadiumID": 47,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 0,
      "ConferenceLosses": 9,
      "GlobalTeamID": 50000102,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/102.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }, {
      "TeamID": 96,
      "Key": "WISC",
      "Active": true,
      "School": "Wisconsin",
      "Name": "Badgers",
      "StadiumID": 96,
      "ApRank": 7,
      "Wins": 13,
      "Losses": 1,
      "ConferenceWins": 9,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000096,
      "CoachesRank": 6,
      "PlayoffRank": 6,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/96.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }, {
      "TeamID": 99,
      "Key": "NEBR",
      "Active": true,
      "School": "Nebraska",
      "Name": "Cornhuskers",
      "StadiumID": 72,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 3,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000099,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/99.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }, {
      "TeamID": 100,
      "Key": "NW",
      "Active": true,
      "School": "Northwestern",
      "Name": "Wildcats",
      "StadiumID": 32,
      "ApRank": 17,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000100,
      "CoachesRank": 17,
      "PlayoffRank": 21,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/100.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }, {
      "TeamID": 94,
      "Key": "PUR",
      "Active": true,
      "School": "Purdue",
      "Name": "Boilermakers",
      "StadiumID": 30,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000094,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/94.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }, {
      "TeamID": 91,
      "Key": "IOWA",
      "Active": true,
      "School": "Iowa",
      "Name": "Hawkeyes",
      "StadiumID": 45,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 4,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000091,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/91.png",
      "ConferenceID": 7,
      "Conference": "Big Ten - West"
    }]
  }, {
    "ConferenceID": 8,
    "Name": "East",
    "Teams": [{
      "TeamID": 135,
      "Key": "MTNST",
      "Active": true,
      "School": "Middle Tennessee",
      "Name": "Blue Raiders",
      "StadiumID": 59,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000135,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/135.png",
      "ConferenceID": 8,
      "Conference": "East"
    }, {
      "TeamID": 136,
      "Key": "MARSH",
      "Active": true,
      "School": "Marshall",
      "Name": "Thundering Herd",
      "StadiumID": 103,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000136,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/136.png",
      "ConferenceID": 8,
      "Conference": "East"
    }, {
      "TeamID": 138,
      "Key": "OLD",
      "Active": true,
      "School": "Old Dominion",
      "Name": "Monarchs",
      "StadiumID": 52,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000138,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/138.png",
      "ConferenceID": 8,
      "Conference": "East"
    }, {
      "TeamID": 140,
      "Key": "FLINT",
      "Active": true,
      "School": "Florida Intl",
      "Name": "Golden Panthers",
      "StadiumID": 7,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000140,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/140.png",
      "ConferenceID": 8,
      "Conference": "East"
    }, {
      "TeamID": 144,
      "Key": "WKENT",
      "Active": true,
      "School": "Western Kentucky",
      "Name": "Hilltoppers",
      "StadiumID": 12,
      "ApRank": null,
      "Wins": 6,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000144,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/144.png",
      "ConferenceID": 8,
      "Conference": "East"
    }, {
      "TeamID": 145,
      "Key": "FLATL",
      "Active": true,
      "School": "Florida Atlantic",
      "Name": "Owls",
      "StadiumID": 51,
      "ApRank": null,
      "Wins": 11,
      "Losses": 3,
      "ConferenceWins": 8,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000145,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/145.png",
      "ConferenceID": 8,
      "Conference": "East"
    }, {
      "TeamID": 142,
      "Key": "CHARLT",
      "Active": true,
      "School": "Charlotte",
      "Name": "49ers",
      "StadiumID": 161,
      "ApRank": null,
      "Wins": 1,
      "Losses": 11,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000142,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/142.png",
      "ConferenceID": 8,
      "Conference": "East"
    }]
  }, {
    "ConferenceID": 9,
    "Name": "West",
    "Teams": [{
      "TeamID": 143,
      "Key": "SOUMIS",
      "Active": true,
      "School": "Southern Mississippi",
      "Name": "Golden Eagles",
      "StadiumID": 109,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000143,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/143.png",
      "ConferenceID": 9,
      "Conference": "West"
    }, {
      "TeamID": 146,
      "Key": "RICE",
      "Active": true,
      "School": "Rice",
      "Name": "Owls",
      "StadiumID": 120,
      "ApRank": null,
      "Wins": 1,
      "Losses": 11,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000146,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/146.png",
      "ConferenceID": 9,
      "Conference": "West"
    }, {
      "TeamID": 147,
      "Key": "UTSA",
      "Active": true,
      "School": "UT San Antonio",
      "Name": "Roadrunners",
      "StadiumID": 66,
      "ApRank": null,
      "Wins": 6,
      "Losses": 5,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000147,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/147.png",
      "ConferenceID": 9,
      "Conference": "West"
    }, {
      "TeamID": 141,
      "Key": "NTX",
      "Active": true,
      "School": "North Texas",
      "Name": "Mean Green",
      "StadiumID": 60,
      "ApRank": null,
      "Wins": 9,
      "Losses": 5,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000141,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/141.png",
      "ConferenceID": 9,
      "Conference": "West"
    }, {
      "TeamID": 139,
      "Key": "UTEP",
      "Active": true,
      "School": "UTEP",
      "Name": "Miners",
      "StadiumID": 74,
      "ApRank": null,
      "Wins": 0,
      "Losses": 12,
      "ConferenceWins": 0,
      "ConferenceLosses": 8,
      "GlobalTeamID": 50000139,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/139.png",
      "ConferenceID": 9,
      "Conference": "West"
    }, {
      "TeamID": 137,
      "Key": "LOUTCH",
      "Active": true,
      "School": "Louisiana Tech",
      "Name": "Bulldogs",
      "StadiumID": 108,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000137,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/137.png",
      "ConferenceID": 9,
      "Conference": "West"
    }, {
      "TeamID": 134,
      "Key": "UAB",
      "Active": true,
      "School": "UAB",
      "Name": "Blazers",
      "StadiumID": 155,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000134,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/134.png",
      "ConferenceID": 9,
      "Conference": "West"
    }]
  }, {
    "ConferenceID": 10,
    "Name": "FBS Independents",
    "Teams": [{
      "TeamID": 25,
      "Key": "ND",
      "Active": true,
      "School": "Notre Dame",
      "Name": "Fighting Irish",
      "StadiumID": 97,
      "ApRank": 11,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 0,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000025,
      "CoachesRank": 11,
      "PlayoffRank": 14,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/25.png",
      "ConferenceID": 10,
      "Conference": "FBS Independents"
    }, {
      "TeamID": 55,
      "Key": "UMASS",
      "Active": true,
      "School": "UMass",
      "Name": "Minutemen",
      "StadiumID": 126,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 0,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000055,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/55.png",
      "ConferenceID": 10,
      "Conference": "FBS Independents"
    }, {
      "TeamID": 263,
      "Key": "ARMY",
      "Active": true,
      "School": "Army",
      "Name": "Black Knights",
      "StadiumID": 86,
      "ApRank": null,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 0,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000263,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/263.png",
      "ConferenceID": 10,
      "Conference": "FBS Independents"
    }, {
      "TeamID": 336,
      "Key": "BYU",
      "Active": true,
      "School": "BYU",
      "Name": "Cougars",
      "StadiumID": 131,
      "ApRank": null,
      "Wins": 4,
      "Losses": 9,
      "ConferenceWins": 0,
      "ConferenceLosses": 0,
      "GlobalTeamID": 50000336,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/336.png",
      "ConferenceID": 10,
      "Conference": "FBS Independents"
    }]
  }, {
    "ConferenceID": 11,
    "Name": "Mid-American - East",
    "Teams": [{
      "TeamID": 177,
      "Key": "AKRON",
      "Active": true,
      "School": "Akron",
      "Name": "Zips",
      "StadiumID": 58,
      "ApRank": null,
      "Wins": 7,
      "Losses": 7,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000177,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/177.png",
      "ConferenceID": 11,
      "Conference": "Mid-American - East"
    }, {
      "TeamID": 178,
      "Key": "KENTST",
      "Active": true,
      "School": "Kent State",
      "Name": "Golden Flashes",
      "StadiumID": 160,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000178,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/178.png",
      "ConferenceID": 11,
      "Conference": "Mid-American - East"
    }, {
      "TeamID": 179,
      "Key": "BUF",
      "Active": true,
      "School": "Buffalo",
      "Name": "Bulls",
      "StadiumID": 19,
      "ApRank": null,
      "Wins": 6,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000179,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/179.png",
      "ConferenceID": 11,
      "Conference": "Mid-American - East"
    }, {
      "TeamID": 180,
      "Key": "OHIO",
      "Active": true,
      "School": "Ohio",
      "Name": "Bobcats",
      "StadiumID": 46,
      "ApRank": null,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000180,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/180.png",
      "ConferenceID": 11,
      "Conference": "Mid-American - East"
    }, {
      "TeamID": 181,
      "Key": "BOWLGR",
      "Active": true,
      "School": "Bowling Green",
      "Name": "Falcons",
      "StadiumID": 93,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000181,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/181.png",
      "ConferenceID": 11,
      "Conference": "Mid-American - East"
    }, {
      "TeamID": 182,
      "Key": "MIAOH",
      "Active": true,
      "School": "Miami (OH)",
      "Name": "RedHawks",
      "StadiumID": 94,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000182,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/182.png",
      "ConferenceID": 11,
      "Conference": "Mid-American - East"
    }]
  }, {
    "ConferenceID": 12,
    "Name": "Mid-American - West",
    "Teams": [{
      "TeamID": 183,
      "Key": "TOLEDO",
      "Active": true,
      "School": "Toledo",
      "Name": "Rockets",
      "StadiumID": 107,
      "ApRank": null,
      "Wins": 11,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000183,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/183.png",
      "ConferenceID": 12,
      "Conference": "Mid-American - West"
    }, {
      "TeamID": 184,
      "Key": "BALLST",
      "Active": true,
      "School": "Ball State",
      "Name": "Cardinals",
      "StadiumID": 124,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 0,
      "ConferenceLosses": 8,
      "GlobalTeamID": 50000184,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/184.png",
      "ConferenceID": 12,
      "Conference": "Mid-American - West"
    }, {
      "TeamID": 185,
      "Key": "CMICH",
      "Active": true,
      "School": "Central Michigan",
      "Name": "Chippewas",
      "StadiumID": 2,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000185,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/185.png",
      "ConferenceID": 12,
      "Conference": "Mid-American - West"
    }, {
      "TeamID": 186,
      "Key": "NILL",
      "Active": true,
      "School": "Northern Illinois",
      "Name": "Huskies",
      "StadiumID": 125,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000186,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/186.png",
      "ConferenceID": 12,
      "Conference": "Mid-American - West"
    }, {
      "TeamID": 187,
      "Key": "EMICH",
      "Active": true,
      "School": "Eastern Michigan",
      "Name": "Eagles",
      "StadiumID": 17,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000187,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/187.png",
      "ConferenceID": 12,
      "Conference": "Mid-American - West"
    }, {
      "TeamID": 188,
      "Key": "WMICH",
      "Active": true,
      "School": "Western Michigan",
      "Name": "Broncos",
      "StadiumID": 106,
      "ApRank": null,
      "Wins": 6,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000188,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/188.png",
      "ConferenceID": 12,
      "Conference": "Mid-American - West"
    }]
  }, {
    "ConferenceID": 13,
    "Name": "Mountain West - Mountain",
    "Teams": [{
      "TeamID": 219,
      "Key": "WYOM",
      "Active": true,
      "School": "Wyoming",
      "Name": "Cowboys",
      "StadiumID": 80,
      "ApRank": null,
      "Wins": 8,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000219,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/219.png",
      "ConferenceID": 13,
      "Conference": "Mountain West - Mountain"
    }, {
      "TeamID": 220,
      "Key": "UTAHST",
      "Active": true,
      "School": "Utah State",
      "Name": "Aggies",
      "StadiumID": 11,
      "ApRank": null,
      "Wins": 6,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000220,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/220.png",
      "ConferenceID": 13,
      "Conference": "Mountain West - Mountain"
    }, {
      "TeamID": 221,
      "Key": "AIRF",
      "Active": true,
      "School": "Air Force",
      "Name": "Falcons",
      "StadiumID": 40,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000221,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/221.png",
      "ConferenceID": 13,
      "Conference": "Mountain West - Mountain"
    }, {
      "TeamID": 217,
      "Key": "COLST",
      "Active": true,
      "School": "Colorado State",
      "Name": "Rams",
      "StadiumID": 165,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000217,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/217.png",
      "ConferenceID": 13,
      "Conference": "Mountain West - Mountain"
    }, {
      "TeamID": 214,
      "Key": "NMX",
      "Active": true,
      "School": "New Mexico",
      "Name": "Lobos",
      "StadiumID": 14,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000214,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/214.png",
      "ConferenceID": 13,
      "Conference": "Mountain West - Mountain"
    }, {
      "TeamID": 215,
      "Key": "BOISE",
      "Active": true,
      "School": "Boise State",
      "Name": "Broncos",
      "StadiumID": 117,
      "ApRank": 22,
      "Wins": 11,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000215,
      "CoachesRank": 22,
      "PlayoffRank": 25,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/215.png",
      "ConferenceID": 13,
      "Conference": "Mountain West - Mountain"
    }]
  }, {
    "ConferenceID": 14,
    "Name": "Mountain West - West",
    "Teams": [{
      "TeamID": 216,
      "Key": "NEVADA",
      "Active": true,
      "School": "Nevada",
      "Name": "Wolf Pack",
      "StadiumID": 26,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000216,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/216.png",
      "ConferenceID": 14,
      "Conference": "Mountain West - West"
    }, {
      "TeamID": 218,
      "Key": "UNLV",
      "Active": true,
      "School": "UNLV",
      "Name": "Rebels",
      "StadiumID": 16,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000218,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/218.png",
      "ConferenceID": 14,
      "Conference": "Mountain West - West"
    }, {
      "TeamID": 222,
      "Key": "SJST",
      "Active": true,
      "School": "San Jose State",
      "Name": "Spartans",
      "StadiumID": 101,
      "ApRank": null,
      "Wins": 2,
      "Losses": 11,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000222,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/222.png",
      "ConferenceID": 14,
      "Conference": "Mountain West - West"
    }, {
      "TeamID": 212,
      "Key": "SDST",
      "Active": true,
      "School": "San Diego State",
      "Name": "Aztecs",
      "StadiumID": 77,
      "ApRank": null,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000212,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/212.png",
      "ConferenceID": 14,
      "Conference": "Mountain West - West"
    }, {
      "TeamID": 213,
      "Key": "FREST",
      "Active": true,
      "School": "Fresno State",
      "Name": "Bulldogs",
      "StadiumID": 116,
      "ApRank": null,
      "Wins": 10,
      "Losses": 4,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000213,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/213.png",
      "ConferenceID": 14,
      "Conference": "Mountain West - West"
    }, {
      "TeamID": 115,
      "Key": "HAWAII",
      "Active": true,
      "School": "Hawaii",
      "Name": "Rainbow Warriors",
      "StadiumID": 119,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000115,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/115.png",
      "ConferenceID": 14,
      "Conference": "Mountain West - West"
    }]
  }, {
    "ConferenceID": 15,
    "Name": "Pac 12 - North",
    "Teams": [{
      "TeamID": 249,
      "Key": "WASH",
      "Active": true,
      "School": "Washington",
      "Name": "Huskies",
      "StadiumID": 41,
      "ApRank": 16,
      "Wins": 10,
      "Losses": 3,
      "ConferenceWins": 7,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000249,
      "CoachesRank": 15,
      "PlayoffRank": 11,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/249.png",
      "ConferenceID": 15,
      "Conference": "Pac 12 - North"
    }, {
      "TeamID": 256,
      "Key": "WASHST",
      "Active": true,
      "School": "Washington State",
      "Name": "Cougars",
      "StadiumID": 73,
      "ApRank": null,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 6,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000256,
      "CoachesRank": null,
      "PlayoffRank": 18,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/256.png",
      "ConferenceID": 15,
      "Conference": "Pac 12 - North"
    }, {
      "TeamID": 251,
      "Key": "CAH",
      "Active": true,
      "School": "California",
      "Name": "Golden Bears",
      "StadiumID": 132,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 2,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000251,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/251.png",
      "ConferenceID": 15,
      "Conference": "Pac 12 - North"
    }, {
      "TeamID": 252,
      "Key": "OREGST",
      "Active": true,
      "School": "Oregon State",
      "Name": "Beavers",
      "StadiumID": 129,
      "ApRank": null,
      "Wins": 1,
      "Losses": 11,
      "ConferenceWins": 0,
      "ConferenceLosses": 9,
      "GlobalTeamID": 50000252,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/252.png",
      "ConferenceID": 15,
      "Conference": "Pac 12 - North"
    }, {
      "TeamID": 254,
      "Key": "STAN",
      "Active": true,
      "School": "Stanford",
      "Name": "Cardinal",
      "StadiumID": 24,
      "ApRank": 20,
      "Wins": 9,
      "Losses": 5,
      "ConferenceWins": 7,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000254,
      "CoachesRank": 19,
      "PlayoffRank": 13,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/254.png",
      "ConferenceID": 15,
      "Conference": "Pac 12 - North"
    }, {
      "TeamID": 245,
      "Key": "ORE",
      "Active": true,
      "School": "Oregon",
      "Name": "Ducks",
      "StadiumID": 50,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000245,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/245.png",
      "ConferenceID": 15,
      "Conference": "Pac 12 - North"
    }]
  }, {
    "ConferenceID": 16,
    "Name": "Pac 12 - South",
    "Teams": [{
      "TeamID": 246,
      "Key": "USC",
      "Active": true,
      "School": "USC",
      "Name": "Trojans",
      "StadiumID": 91,
      "ApRank": 12,
      "Wins": 11,
      "Losses": 3,
      "ConferenceWins": 8,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000246,
      "CoachesRank": 10,
      "PlayoffRank": 8,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/246.png",
      "ConferenceID": 16,
      "Conference": "Pac 12 - South"
    }, {
      "TeamID": 247,
      "Key": "ARZ",
      "Active": true,
      "School": "Arizona",
      "Name": "Wildcats",
      "StadiumID": 118,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 5,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000247,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/247.png",
      "ConferenceID": 16,
      "Conference": "Pac 12 - South"
    }, {
      "TeamID": 248,
      "Key": "UTAH",
      "Active": true,
      "School": "Utah",
      "Name": "Utes",
      "StadiumID": 10,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 3,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000248,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/248.png",
      "ConferenceID": 16,
      "Conference": "Pac 12 - South"
    }, {
      "TeamID": 255,
      "Key": "ARZST",
      "Active": true,
      "School": "Arizona State",
      "Name": "Sun Devils",
      "StadiumID": 81,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 6,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000255,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/255.png",
      "ConferenceID": 16,
      "Conference": "Pac 12 - South"
    }, {
      "TeamID": 253,
      "Key": "UCLA",
      "Active": true,
      "School": "UCLA",
      "Name": "Bruins",
      "StadiumID": 114,
      "ApRank": null,
      "Wins": 6,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000253,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/253.png",
      "ConferenceID": 16,
      "Conference": "Pac 12 - South"
    }, {
      "TeamID": 250,
      "Key": "COL",
      "Active": true,
      "School": "Colorado",
      "Name": "Buffaloes",
      "StadiumID": 102,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 2,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000250,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/250.png",
      "ConferenceID": 16,
      "Conference": "Pac 12 - South"
    }]
  }, {
    "ConferenceID": 17,
    "Name": "SEC - East",
    "Teams": [{
      "TeamID": 280,
      "Key": "MISSR",
      "Active": true,
      "School": "Missouri",
      "Name": "Tigers",
      "StadiumID": 110,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000280,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/280.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }, {
      "TeamID": 277,
      "Key": "TENN",
      "Active": true,
      "School": "Tennessee",
      "Name": "Volunteers",
      "StadiumID": 8,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 0,
      "ConferenceLosses": 8,
      "GlobalTeamID": 50000277,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/277.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }, {
      "TeamID": 267,
      "Key": "SC",
      "Active": true,
      "School": "South Carolina",
      "Name": "Gamecocks",
      "StadiumID": 128,
      "ApRank": null,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000267,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/267.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }, {
      "TeamID": 268,
      "Key": "UK",
      "Active": true,
      "School": "Kentucky",
      "Name": "Wildcats",
      "StadiumID": 68,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000268,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/268.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }, {
      "TeamID": 271,
      "Key": "FL",
      "Active": true,
      "School": "Florida",
      "Name": "Gators",
      "StadiumID": 69,
      "ApRank": null,
      "Wins": 4,
      "Losses": 7,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000271,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/271.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }, {
      "TeamID": 272,
      "Key": "GA",
      "Active": true,
      "School": "Georgia",
      "Name": "Bulldogs",
      "StadiumID": 88,
      "ApRank": 2,
      "Wins": 13,
      "Losses": 2,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000272,
      "CoachesRank": 2,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/272.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }, {
      "TeamID": 273,
      "Key": "VAND",
      "Active": true,
      "School": "Vanderbilt",
      "Name": "Commodores",
      "StadiumID": 9,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000273,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/273.png",
      "ConferenceID": 17,
      "Conference": "SEC - East"
    }]
  }, {
    "ConferenceID": 18,
    "Name": "SEC - West",
    "Teams": [{
      "TeamID": 274,
      "Key": "MISS",
      "Active": true,
      "School": "Ole Miss",
      "Name": "Rebels",
      "StadiumID": 99,
      "ApRank": null,
      "Wins": 6,
      "Losses": 6,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000274,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/274.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }, {
      "TeamID": 275,
      "Key": "ALA",
      "Active": true,
      "School": "Alabama",
      "Name": "Crimson Tide",
      "StadiumID": 98,
      "ApRank": 1,
      "Wins": 13,
      "Losses": 1,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000275,
      "CoachesRank": 1,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/275.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }, {
      "TeamID": 276,
      "Key": "ARK",
      "Active": true,
      "School": "Arkansas",
      "Name": "Razorbacks",
      "StadiumID": 49,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000276,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/276.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }, {
      "TeamID": 269,
      "Key": "LSU",
      "Active": true,
      "School": "LSU",
      "Name": "Tigers",
      "StadiumID": 111,
      "ApRank": 18,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000269,
      "CoachesRank": 18,
      "PlayoffRank": 17,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/269.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }, {
      "TeamID": 270,
      "Key": "TXAM",
      "Active": true,
      "School": "Texas A&M",
      "Name": "Aggies",
      "StadiumID": 42,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000270,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/270.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }, {
      "TeamID": 278,
      "Key": "MSPST",
      "Active": true,
      "School": "Mississippi State",
      "Name": "Bulldogs",
      "StadiumID": 35,
      "ApRank": 19,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000278,
      "CoachesRank": 20,
      "PlayoffRank": 23,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/278.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }, {
      "TeamID": 279,
      "Key": "AUBRN",
      "Active": true,
      "School": "Auburn",
      "Name": "Tigers",
      "StadiumID": 78,
      "ApRank": 10,
      "Wins": 10,
      "Losses": 4,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000279,
      "CoachesRank": 12,
      "PlayoffRank": 7,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/279.png",
      "ConferenceID": 18,
      "Conference": "SEC - West"
    }]
  }, {
    "ConferenceID": 19,
    "Name": "Sun Belt Conference",
    "Teams": [{
      "TeamID": 344,
      "Key": "NMXST",
      "Active": true,
      "School": "New Mexico State",
      "Name": "Aggies",
      "StadiumID": 115,
      "ApRank": null,
      "Wins": 7,
      "Losses": 6,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000344,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/344.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 324,
      "Key": "LOULAF",
      "Active": true,
      "School": "Louisiana",
      "Name": "Ragin Cajuns",
      "StadiumID": 34,
      "ApRank": null,
      "Wins": 5,
      "Losses": 7,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000324,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/324.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 326,
      "Key": "LAMON",
      "Active": true,
      "School": "UL Monroe",
      "Name": "Warhawks",
      "StadiumID": 67,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 4,
      "ConferenceLosses": 4,
      "GlobalTeamID": 50000326,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/326.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 327,
      "Key": "ARKST",
      "Active": true,
      "School": "Arkansas State",
      "Name": "Red Wolves",
      "StadiumID": 25,
      "ApRank": null,
      "Wins": 7,
      "Losses": 5,
      "ConferenceWins": 6,
      "ConferenceLosses": 2,
      "GlobalTeamID": 50000327,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/327.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 328,
      "Key": "GAST",
      "Active": true,
      "School": "Georgia State",
      "Name": "Panthers",
      "StadiumID": 166,
      "ApRank": null,
      "Wins": 7,
      "Losses": 5,
      "ConferenceWins": 5,
      "ConferenceLosses": 3,
      "GlobalTeamID": 50000328,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/328.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 329,
      "Key": "GAS",
      "Active": true,
      "School": "Georgia Southern",
      "Name": "Eagles",
      "StadiumID": 56,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000329,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/329.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 330,
      "Key": "SALA",
      "Active": true,
      "School": "South Alabama",
      "Name": "Jaguars",
      "StadiumID": 104,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000330,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/330.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 331,
      "Key": "APPLST",
      "Active": true,
      "School": "Appalachian State",
      "Name": "Mountaineers",
      "StadiumID": 95,
      "ApRank": null,
      "Wins": 9,
      "Losses": 4,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000331,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/331.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 332,
      "Key": "TXST",
      "Active": true,
      "School": "Texas State",
      "Name": "Bobcats",
      "StadiumID": 135,
      "ApRank": null,
      "Wins": 2,
      "Losses": 10,
      "ConferenceWins": 1,
      "ConferenceLosses": 7,
      "GlobalTeamID": 50000332,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/332.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 333,
      "Key": "TROY",
      "Active": true,
      "School": "Troy",
      "Name": "Trojans",
      "StadiumID": 57,
      "ApRank": null,
      "Wins": 11,
      "Losses": 2,
      "ConferenceWins": 7,
      "ConferenceLosses": 1,
      "GlobalTeamID": 50000333,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/333.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 81,
      "Key": "COAST",
      "Active": true,
      "School": "Coastal Carolina",
      "Name": "Chanticleers",
      "StadiumID": 167,
      "ApRank": null,
      "Wins": 3,
      "Losses": 9,
      "ConferenceWins": 2,
      "ConferenceLosses": 6,
      "GlobalTeamID": 50000081,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/81.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }, {
      "TeamID": 73,
      "Key": "IDAHO",
      "Active": true,
      "School": "Idaho",
      "Name": "Vandals",
      "StadiumID": 15,
      "ApRank": null,
      "Wins": 4,
      "Losses": 8,
      "ConferenceWins": 3,
      "ConferenceLosses": 5,
      "GlobalTeamID": 50000073,
      "CoachesRank": null,
      "PlayoffRank": null,
      "TeamLogoUrl": "https:\/\/s3-us-west-2.amazonaws.com\/static.fantasydata.com\/logos\/ncaa\/73.png",
      "ConferenceID": 19,
      "Conference": "Sun Belt Conference"
    }]
  }]

let current_conf = [
  {conference_id:10501,fantasy_data_key:3, name: 'Atlantic'},
  {conference_id:10503,fantasy_data_key:5, name: 'Big 12 Conference'},
  {conference_id:10504,fantasy_data_key:6, name: 'Big Ten - East'},
  {conference_id:10505,fantasy_data_key:7, name: 'Big Ten - West'},
  {conference_id:10506,fantasy_data_key:15, name: 'Pac-12 North'},
  {conference_id:10507,fantasy_data_key:16, name: 'Pac-12 South'},
  {conference_id:10508,fantasy_data_key:17, name: 'SEC - East'},
  {conference_id:10509,fantasy_data_key:18, name: 'SEC - West'},
  {conference_id:10510,fantasy_data_key:10, name: 'FBS Independents'}]

conferences_already = [3,5,6, 7, 15, 16, 17, 18, 10]

let x = 10511
let y = 10501

  let for_sports_conferences_table = data.map(conference => {
    const conf_id = conferences_already.includes(conference.ConferenceID) ? (
        y, y++
    ) : conference.ConferenceID === 4 ? (
        '10502', y++) : (
        x, x++
    )
    return {conference_id: conf_id, fantasy_data_key: conference.ConferenceID, name: conference.Name}
    //return {conference_id: conf_id, name: conference.Name, display_name:conference.Name}
})

console.log(for_sports_conferences_table)

