const constants = {
  SHOW_MOBILE_NAV: 'SHOW_MOBILE_NAV',
  HIDE_MOBILE_NAV: 'HIDE_MOBILE_NAV',
  TOGGLE_MOBILE_NAV: 'TOGGLE_MOBILE_NAV',
  DATA_LOAD_SUCCESS:'DATA_LOAD_SUCCESS',

  PRESSED_LOGIN : 'PRESSED_LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_USERNAME_FAIL: 'FORGOT_USERNAME_FAIL',
  FORGOT_USERNAME_SUCCESS: 'FORGOT_USERNAME_SUCCESS',
  CREATE_PASSWORD_FAIL: 'CREATE_PASSWORD_FAIL',
  CREATE_PASSWORD_SUCCESS: 'CREATE_PASSWORD_SUCCESS',
  FORCED_LOGIN: 'FORCED_LOGIN',
  UPDATE_ERROR: 'UPDATE_ERROR',

  UPDATE_TEAM_UPDATE_TIME:'UPDATE_TEAM_UPDATE_TIME',
  UPDATE_TEAMS:'UPDATE_TEAMS',
  UPDATE_TEAM_DIFF:'UPDATE_TEAM_DIFF',
  UPDATE_GAME_UPDATE_TIME:'UPDATE_GAME_UPDATE_TIME',
  UPDATE_GAMES:'UPDATE_GAMES',
  UPDATE_GAME_DIFF:'UPDATE_GAME_DIFF',

  CREATE_LEAGUE_FAIL: 'CREATE_LEAGUE_FAIL',
  CREATE_LEAGUE_SUCCESS: 'CREATE_LEAGUE_SUCCESS',
  JOIN_LEAGUE_FAIL : 'JOIN_LEAGUE_FAIL',
  JOIN_LEAGUE_SUCCESS : 'JOIN_LEAGUE_SUCCESS',

  SAVE_OWNER_SETTINGS_SUCCESS : 'SAVE_OWNER_SETTINGS_SUCCESS',
  SAVE_OWNER_SETTINGS_FAIL : 'SAVE_OWNER_SETTINGS_FAIL',

  CLICKED_LEAGUE : 'CLICKED_LEAGUE',
  GET_TEAMS: 'GET_TEAMS',
  GET_SPORT_LEAGUES: 'GET_SPORT_LEAGUES',
  GET_SCHEDULE_BY_DAY: 'GET_SCHEDULE_BY_DAY',
  GET_ONE_TEAM: 'GET_ONE_TEAM',
  GET_SPORT_SEASONS: 'GET_SPORT_SEASONS',

  UPDATE_DRAFT_ORDER: 'UPDATE_DRAFT_ORDER',
  ENTERED_DRAFT: 'ENTERED_DRAFT',
  START_DRAFT: 'START_DRAFT',
  SAVED_DRAFT: 'SAVED_DRAFT',
  UPDATE_DRAFT_MODE : 'UPDATE_DRAFT_MODE',
  DRAFT_PICK : 'DRAFT_PICK',
  UPDATE_DRAFT_QUEUE : 'UPDATE_DRAFT_QUEUE',
  FILTER_TAB: 'FILTER_TAB',
  OPEN_DIALOG: 'OPEN_DIALOG',
  CLOSE_DIALOG: 'CLOSE_DIALOG',
  UPDATE_DIALOG: 'UPDATE_DIALOG',
  RECIEVED_DRAFT_MESSAGE : 'RECIEVED_DRAFT_MESSAGE',
  
  CLEAR_FILTERS: 'CLEAR_FILTERS',
  UPDATE_FILTER: 'UPDATE_FILTER',
  REMOVE_FILTER : 'REMOVE_FILTER',

  SB: {
    'EHBS': 'Email has been sent.',
    'YHSCUPPL': 'You have successfully changed your password, please login.'
  },

  MAKE_PROGRESS : 'MAKE_PROGRESS',

  PAGES:{
    CREATE_LEAGUE : 'CREATE_LEAGUE',
    JOIN_LEAGUE : 'JOIN_LEAGUE',
    CUSTOMIZE_TEAMS : 'CUSTOMIZE_TEAMS',
    COMMISH_TOOLS : 'COMMISH_TOOLS'
  },

  DRAFT_STATE : {
    PRE : 'pre',
    LIVE : 'live',
    TIMEOUT : 'timeout',
    POST : 'post'
  }
}

module.exports = constants