const constants = {
  ADD_COLOR: 'ADD_COLOR',
  RATE_COLOR: 'RATE_COLOR',
  REMOVE_COLOR: 'REMOVE_COLOR',

  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  CREATE_LEAGUE_FAIL: 'CREATE_LEAGUE_FAIL',
  CREATE_LEAGUE_SUCCESS: 'CREATE_LEAGUE_SUCCESS',
  JOIN_LEAGUE_FAIL : 'JOIN_LEAGUE_FAIL',
  JOIN_LEAGUE_SUCCESS : 'JOIN_LEAGUE_SUCCESS',
  CLICKED_LEAGUE : 'CLICKED_LEAGUE',

  GET_TEAMS: 'GET_TEAMS'
}

module.exports = constants