const constants = {
  DATA_LOAD_SUCCESS:'DATA_LOAD_SUCCESS',

  PRESSED_LOGIN : 'PRESSED_LOGIN',
  LOGOUT: 'LOGOUT',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  FORGOT_PASSWORD_FAIL: 'FORGOT_PASSWORD_FAIL',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  CREATE_PASSWORD_FAIL: 'CREATE_PASSWORD_FAIL',
  CREATE_PASSWORD_SUCCESS: 'CREATE_PASSWORD_SUCCESS',
  FORCED_LOGIN: 'FORCED_LOGIN',

  CREATE_LEAGUE_FAIL: 'CREATE_LEAGUE_FAIL',
  CREATE_LEAGUE_SUCCESS: 'CREATE_LEAGUE_SUCCESS',
  JOIN_LEAGUE_FAIL : 'JOIN_LEAGUE_FAIL',
  JOIN_LEAGUE_SUCCESS : 'JOIN_LEAGUE_SUCCESS',

  CLICKED_LEAGUE : 'CLICKED_LEAGUE',
  GET_TEAMS: 'GET_TEAMS',
  GET_SPORT_LEAGUES: 'GET_SPORT_LEAGUES',
  GET_SCHEDULE_BY_DAY: 'GET_SCHEDULE_BY_DAY',

  UPDATE_DRAFT_ORDER: 'UPDATE_DRAFT_ORDER',
  SAVED_DRAFT: 'SAVED_DRAFT'
}

module.exports = constants